//! App Module - 
export const MOBILE_WIDTH = "MOBILE_DEVICE_WIDTH";
export const MOBILE_HEIGHT = "MOBILE_DEVICE_HEIGHT";
export const TABLET_WIDTH = "TABLET_DEVICE_WIDTH";
export const GENERAL_DESKTOP_WIDTH = "GENERAL_DESKTOP_WIDTH";
export const MID_DESKTOP_WIDTH = "MID_DESKTOP_DEVICE_WIDTH";
export const LARGE_DESKTOP_WIDTH = "LARGE_DESKTOP_WIDTH";
export const GET_NEW_MESSAGE = "GET_NEW_MESSAGE";
export const PAGE_VISIBILITY_READY = "PAGE_VISIBILITY_READY";
export const GET_INTERSECTION_OBSERVER = "GET_INTERSECTION_OBSERVER";

//! Auth Module
export const IS_LANDLORD = "IS_LANDLORD";
export const IS_TENANT = "IS_TENANT";
export const IS_ADMIN = "IS_ADMIN";
export const CHECK_AUTHENTICATION = "CHECK_AUTHENTICATION";
export const CHECK_VERIFICATION = "CHECK_VERIFICATION";